--- # local
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    username: sgkang
    password: sgkang

server:
  port: 8080

--- # dev
spring:
  profiles: dev
server:
  port: 8090
--- # prod
spring:
  profiles: prod
server:
  port: 80