--- # local
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    username: sgkang
    password: sgkang

mybatis:
  mapper-locations: classpath*:/sql/*.xml
  type-aliases-package: com.ksg.openapi.sample.errorResponse
  type-handlers-package: com.ksg.openapi.sample.errorResponse
  configuration:
    cache-enabled: false
    use-generated-keys: true
    default-executor-type: reuse

server:
  port: 8080

--- # dev
spring:
  profiles: dev
server:
  port: 8090
--- # prod
spring:
  profiles: prod
server:
  port: 80